const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    INCREASE_CORRECT_WORDS: 'INCREASE_CORRECT_WORDS',
    INCREASE_WRONG_WORDS: 'DECREASE_WRONG_WRODS',
    RELOAD_WPM: 'RELOAD_WPM'
})

export default actionTypes;